#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [3]:
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
df = pd.read_csv('drive/MyDrive/supermarket_sales.csv')
type (df)

pandas.core.frame.DataFrame

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [6]:
df.groupby(by =['Branch'])['Total'].sum()

Branch
A    106200.3705
B    106197.6720
C    110568.7065
Name: Total, dtype: float64

Найвищий прибуток має філіал С - 110568.71

In [7]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [8]:
df.groupby(by =['Branch','City'])['Total'].sum()

Branch  City
A       Yangon       106200.3705
B       Mandalay     106197.6720
C       Naypyitaw    110568.7065
Name: Total, dtype: float64

In [9]:
df.groupby(by =['Branch','City', 'Gender'])['Gender'].count()

Branch  City       Gender
A       Yangon     Female    161
                   Male      179
B       Mandalay   Female    162
                   Male      170
C       Naypyitaw  Female    178
                   Male      150
Name: Gender, dtype: int64

In [10]:
df.groupby(by =['Branch','City', 'Product line'])['Product line'].count()

Branch  City       Product line
A       Yangon     Electronic accessories    60
                   Fashion accessories       51
                   Food and beverages        58
                   Health and beauty         47
                   Home and lifestyle        65
                   Sports and travel         59
B       Mandalay   Electronic accessories    55
                   Fashion accessories       62
                   Food and beverages        50
                   Health and beauty         53
                   Home and lifestyle        50
                   Sports and travel         62
C       Naypyitaw  Electronic accessories    55
                   Fashion accessories       65
                   Food and beverages        66
                   Health and beauty         52
                   Home and lifestyle        45
                   Sports and travel         45
Name: Product line, dtype: int64

У місті Naypyitaw знаходиться філіал з найбільшим прибутком - 110568.71.

В цьому місті ми можемо відкрити ще один магазин, та продавати товари, які користуються більшим попитом у жінок (Fashion accessories, Food and beverages, Health and beauty).

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [11]:
invoices_by_category = pd.pivot_table(df,values= 'Invoice ID', index = 'Branch', columns = 'Product line', aggfunc = 'count')

In [37]:
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [12]:
invoices_by_category.columns

Index(['Electronic accessories', 'Fashion accessories', 'Food and beverages',
       'Health and beauty', 'Home and lifestyle', 'Sports and travel'],
      dtype='object', name='Product line')

In [13]:
invoices_by_category[['Electronic accessories']]

Product line  Electronic accessories
Branch
A                                 60
B                                 55
C                                 55

In [14]:
invoices_by_category['Electronic accessories'].idxmax()

'A'

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

Гіпотеза1. Яка категорія має найбільшу популярність (максимум в одному філіалі)?

In [25]:
invoices_by_category.max(axis=0).idxmax()

'Food and beverages'

- Використовувати як "магніт" для клієнтів
- Робити акції навколо цієї категорії

Гіпотеза 2. У якому філіалі найбільший розрив між найкращою і найгіршою категорією?

In [16]:
(invoices_by_category.max(axis=1) - invoices_by_category.min(axis=1)).idxmax()

'C'

- Нерівномірний попит
- або розвивати слабкі категорії, або фокус на сильних

Гіпотеза 3. Яка категорія має найменший розкид між філіалами (найбільш передбачувана)?

In [26]:
(invoices_by_category.max(axis=0) - invoices_by_category.min(axis=0)).idxmin()

'Electronic accessories'

- Найбільш стабільний товар
- добре підходить для прогнозування та планування запасів

Гіпотеза 4. Яка категорія має найменший загальний попит?

In [27]:
invoices_by_category.sum(axis=0).idxmin()

'Health and beauty'

Треба:
- або зменшити інвестиції
- або перезапустити категорію (акції, ребрендинг)

Гіпотеза 5. Який філіал має найменший загальний обсяг продажів?

In [24]:
invoices_by_category.sum(axis=1).idxmin()

'C'

Філіал С потребує:
- додаткового маркетингу
- перегляду асортименту
- аналізу конкурентів

Висновок:
Ці гіпотези дозволяють:
- оцінити ризики (залежність від категорій)
- зрозуміти стабільність бізнесу
- знайти точки росту і проблемні зони філіалів
- визначити стабільні та ризикові категорії
- адаптувати стратегію під кожен магазин

A — стабільний
B — потребує посилення
C — має сильні перекоси